engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
  # eslint disabled until CodeClimate supports Jasmine & Jasmine-jQuery plugins
  eslint:
    enabled: false
    channel: "eslint-3"
    config: .eslintrc.js
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
  - "**.hbs"
exclude_paths:
- "**/vendor/**/*"
- tests
