---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config: .eslintrc.js
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
  - "**.hbs"
exclude_paths:
- app/styles/vendor/
- app/vendor/
- tests/
