options:
    max-warnings: 50
    formatter: stylish
    merge-default-rules: true

files:
    include: 'app/**/*.scss'
    ignore: 'app/**/vendor/*.*'

rules:
    placeholder-in-extend: 0
    indentation:
        - 2
        - size: 4
    hex-notation:
        - 2
        - style: uppercase