language: node_js

cache:
    bundler: true
    directories:
        - node_modules
        - "travis_phantomjs"

node_js: node

sudo: false

matrix:
    fast_finish: true

#before_install:
#   - rvm install 2.4.0
#   # As of Dec 2016, Travis still doesn't have PhantomJS 2
#   - "phantomjs --version"
#   - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
#   - "phantomjs --version"
#   - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
#   - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
#   - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
#   - "phantomjs --version"

install: travis_retry npm i

before_script:
    - bundle install
#   - ./node_modules/gulp/bin/gulp.js test

script: ./node_modules/gulp/bin/gulp.js

before_deploy: 
    - chmod +x ./travis/addDailyTag.sh
#   - chmod +x ./travis/updateRelease.sh
    - ./travis/addDailyTag.sh
#   - ./travis/updateRelease.sh "$TRAVIS_REPO_SLUG" "`head -1`" ./dist/*

deploy:
    provider: releases
    api_key: $GITHUB_API_KEY
    file: ./dist/*
    skip_cleanup: true
    on:
        tags: true