language: node_js

cache:
  directories:
    - node_modules
    - "travis_phantomjs"

node_js:
  - node

sudo: false

addons:
    code_climate:
        repo_token: accabe6f460082ce8ed6343d6197cf3f738cf8e6e0eade0f20c3686e91415879

matrix:
  fast_finish: true

before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

install: travis_retry npm i --save-dev

before_script:
  - npm i -g codeclimate-test-reporter
  - npm i -g gulp
  - gulp lint
  - npm test

script: gulp build:tidy

after_success:
  - codeclimate-test-reporter < 'coverage/PhantomJS 2.1.1 (Linux 0.0.0)/lcov.info'