language: node_js

cache:
    directories:
        - node_modules
        - travis_phantomjs

node_js: node

sudo: false

matrix:
    fast_finish: true

install: travis_retry npm i

after_install: 
    - npm update
    - npm prune

script: "./node_modules/gulp/bin/gulp.js"

before_deploy:
    - chmod +x ./travis/addDailyTag.sh
     "./travis/addDailyTag.sh"

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "./dist/"
    skip_cleanup: true
    on:
        tags: true
        repo: wopian/hatayama
