language: node_js

cache:
  directories:
    - node_modules

node_js:
  - node

sudo: false

matrix:
  fast_finish: true

before_script:
  - npm i -g gulp

install: travis_retry npm install --save-dev


script: gulp